version: '2'

services:
  app:
    image: 'shops:latest'
    build:
      context: .
    ports:
      - 0.0.0.0:80:8080
    container_name: app
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shops-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shops-db
    volumes:
      - /home/ubuntu/Shops-db:/var/lib/postgresql/data